# Generated by Django 4.2.4 on 2023-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
    ]
