# Generated by Django 4.2.4 on 2023-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0002_task_due_date_task_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='colored_due_date',
            field=models.TextField(null=True),
        ),
    ]
