# Generated by Django 4.2.4 on 2023-08-10 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0003_task_colored_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='colored_due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 23, 16, 27, 561588)),
        ),
    ]
