# Generated by Django 4.2.5 on 2023-09-19 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesTaches', '0005_email_utilisateur_remove_task_colored_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 26, 21, 2, 1, 740200)),
        ),
    ]
